default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: user
  password: password
  host: db

development:
  <<: *default
  database: bbs_app_development

test:
  <<: *default
  database: bbs_app_test

# production:
#   <<: *default
#   database: bbs_app_production
#   username: <%= ENV['DATABASE_USERNAME'] %>
#   password: <%= ENV['DATABASE_PASSWORD'] %>